language: cpp
compiler:
  - gcc
sudo: false
notifications:
    email:
        - colins@eecs.berkeley.edu
cache: apt
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kubuntu-backports
    packages:
    - gcc-4.9
    - g++-4.9
    - gperf
    - autoconf
    - automake
    - autotools-dev
    - libmpc-dev
    - libmpfr-dev
    - libgmp-dev
    - gawk
    - build-essential
    - bison
    - flex
    - texinfo
    - cmake
env:
  global:
    - RISCV="/home/travis/riscv_install"
  matrix:
    - CONFIG="../configure --enable-optimized --enable-targets=riscv --prefix=${RISCV}" TEST="check LIT_ARGS=--filter=.*RISCV.*"
    - CONFIG="cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=RISCV -DCMAKE_INSTALL_PREFIX=${RISCV} ../" TEST="check-llvm-codegen-riscv check-llvm-mc-riscv"
git:
      submodules: true
before_install:
  - export CXX="g++-4.9" CC="gcc-4.9"
  - $CXX --version
script: 
  - mkdir build
  - cd build
  - $CONFIG
  - make -j4
  - make $TEST
